# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='providerupdate',
            old_name='address',
            new_name='primary_address',
        ),
        migrations.AddField(
            model_name='provider',
            name='counties',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('alachua', 'Alachua'), ('baker', 'Baker'), ('bay', 'Bay'), ('bradford', 'Bradford'), ('brevard', 'Brevard'), ('broward', 'Broward'), ('calhoun', 'Calhoun'), ('charlotte', 'Charlotte'), ('citrus', 'Citrus'), ('clay', 'Clay'), ('collier', 'Collier'), ('columbia', 'Columbia'), ('desoto', 'DeSoto'), ('dixie', 'Dixie'), ('duval', 'Duval'), ('escambia', 'Escambia'), ('flagler', 'Flagler'), ('franklin', 'Franklin'), ('gadsden', 'Gadsden'), ('gilchrist', 'Gilchrist'), ('glades', 'Glades'), ('gulf', 'Gulf'), ('hamilton', 'Hamilton'), ('hardee', 'Hardee'), ('hendry', 'Hendry'), ('hernando', 'Hernando'), ('highlands', 'Highlands'), ('hillsborough', 'Hillsborough'), ('holmes', 'Holmes'), ('indian river', 'Indian River'), ('jackson', 'Jackson'), ('jefferson', 'Jefferson'), ('lafayette', 'Lafayette'), ('lake', 'Lake'), ('lee', 'Lee'), ('leon', 'Leon'), ('levy', 'Levy'), ('liberty', 'Liberty'), ('madison', 'Madison'), ('manatee', 'Manatee'), ('marion', 'Marion'), ('martin', 'Martin'), ('miami-dade', 'Miami-Dade'), ('monroe', 'Monroe'), ('nassau', 'Nassau'), ('okaloosa', 'Okaloosa'), ('okeechobee', 'Okeechobee'), ('orange', 'Orange'), ('osceola', 'Osceola'), ('palm_beach', 'Palm Beach'), ('pasco', 'Pasco'), ('pinellas', 'Pinellas'), ('polk', 'Polk'), ('putnam', 'Putnam'), ('santa_rosa', 'Santa Rosa'), ('sarasota', 'Sarasota'), ('seminole', 'Seminole'), ('st_johns', 'St. Johns'), ('st_lucie', 'St. Lucie'), ('sumter', 'Sumter'), ('suwannee', 'Suwannee'), ('taylor', 'Taylor'), ('union', 'Union'), ('volusia', 'Volusia'), ('wakulla', 'Wakulla'), ('walton', 'Walton'), ('washington', 'Washington')], max_length=532, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='primary_address',
            field=models.TextField(null=True, verbose_name='Primary Address'),
        ),
        migrations.AddField(
            model_name='provider',
            name='website_url',
            field=models.CharField(max_length=255, null=True, verbose_name='Website URL'),
        ),
    ]
