# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 21:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_auto_20170524_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='address',
        ),
    ]
