# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_remove_provider_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactperson',
            name='department',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='full_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
