# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0005_auto_20170524_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPersonUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('provider_update', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='providerupdatecontact', to='provider.ProviderUpdate')),
            ],
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='providercontact', to='provider.Provider'),
        ),
    ]
