# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 04:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0006_auto_20170524_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactperson',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='contactpersonupdate',
            name='provider_update',
        ),
        migrations.DeleteModel(
            name='ContactPerson',
        ),
        migrations.DeleteModel(
            name='ContactPersonUpdate',
        ),
    ]
