# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0007_auto_20170524_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='website_url',
            field=models.URLField(max_length=255, null=True, verbose_name='Website URL'),
        ),
        migrations.AlterField(
            model_name='providerupdate',
            name='website_url',
            field=models.URLField(max_length=255, null=True, verbose_name='Website URL'),
        ),
    ]
